
package views;

import controller.CategoriaController;
import controller.LibroController;
import controller.UsuarioController;
import controller.PrestamoController;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.Libro;
import model.Categoria;
import model.Usuario;
import model.Prestamo;

/**
 *
 * @author linki
 */
public class LibroView extends javax.swing.JPanel {

    /**
     * Creates new form LibroView
     */
    public LibroView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablausuarios = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        crearusuario = new javax.swing.JButton();
        actualizarusuario = new javax.swing.JButton();
        leerusuario = new javax.swing.JButton();
        eliminarusuario = new javax.swing.JButton();
        idusuariofield = new javax.swing.JTextField();
        telefonousuariofield = new javax.swing.JTextField();
        nombreusuariofield = new javax.swing.JTextField();
        emailusuariofield = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablalibros = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        crearlibro = new javax.swing.JButton();
        actualizarlibro = new javax.swing.JButton();
        leerlibro = new javax.swing.JButton();
        eliminarlibro = new javax.swing.JButton();
        idlibrofield = new javax.swing.JTextField();
        editoriallibrofield = new javax.swing.JTextField();
        titulolibrofield = new javax.swing.JTextField();
        autorlibrofield = new javax.swing.JTextField();
        añolibrofield = new javax.swing.JTextField();
        isbnlibrofield = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablalibros1 = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        crearcategoria = new javax.swing.JButton();
        actualizarcategoria = new javax.swing.JButton();
        leercategoria = new javax.swing.JButton();
        eliminarcategoria = new javax.swing.JButton();
        idcategoriafield = new javax.swing.JTextField();
        nombrecategoriafield = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tablaprestamos = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        crearprestamo = new javax.swing.JButton();
        actualizarprestamo = new javax.swing.JButton();
        leerprestamo = new javax.swing.JButton();
        eliminarprestamo = new javax.swing.JButton();
        prestamosidfield = new javax.swing.JTextField();
        fechaprestamofield = new javax.swing.JTextField();
        libro_idfield = new javax.swing.JTextField();
        usuario_idfield = new javax.swing.JTextField();
        fechadevolucionfield = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablalibros3 = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        crearlibro_categoria = new javax.swing.JButton();
        actualizarlibro_categoria = new javax.swing.JButton();
        leerlibro_categoria = new javax.swing.JButton();
        eliminarlibro_categoria = new javax.swing.JButton();
        libroidfield = new javax.swing.JTextField();
        categoriaidfield = new javax.swing.JTextField();

        jTabbedPane1.setBackground(new java.awt.Color(255, 153, 204));
        jTabbedPane1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jPanel4.setBackground(new java.awt.Color(255, 204, 204));

        tablausuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id ", "nombre", "email", "telefono"
            }
        ));
        jScrollPane3.setViewportView(tablausuarios);

        jLabel7.setText("Telefono");

        jLabel8.setText("Email");

        jLabel11.setText("Nombre");

        jLabel12.setText("Id Usuario");

        crearusuario.setText("Crear usuario");
        crearusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearusuarioActionPerformed(evt);
            }
        });

        actualizarusuario.setText("Actualizar usuario");
        actualizarusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarusuarioActionPerformed(evt);
            }
        });

        leerusuario.setText("Leer usuario");
        leerusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leerusuarioActionPerformed(evt);
            }
        });

        eliminarusuario.setText("Eliminar usuario");
        eliminarusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarusuarioActionPerformed(evt);
            }
        });

        idusuariofield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idusuariofieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(crearusuario, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(leerusuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(actualizarusuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(eliminarusuario)
                        .addGap(402, 402, 402))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nombreusuariofield, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE)
                                    .addComponent(idusuariofield)
                                    .addComponent(emailusuariofield)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(telefonousuariofield)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(idusuariofield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(nombreusuariofield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(emailusuariofield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(telefonousuariofield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addGap(48, 48, 48)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(crearusuario)
                    .addComponent(leerusuario)
                    .addComponent(actualizarusuario)
                    .addComponent(eliminarusuario))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Usuarios", jPanel4);

        jPanel1.setBackground(new java.awt.Color(255, 204, 255));

        tablalibros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id libro", "Título", "Autor", "Editorial", "Año publicación", "Isbn"
            }
        ));
        jScrollPane1.setViewportView(tablalibros);
        if (tablalibros.getColumnModel().getColumnCount() > 0) {
            tablalibros.getColumnModel().getColumn(2).setHeaderValue("Autor");
            tablalibros.getColumnModel().getColumn(3).setHeaderValue("Editorial");
            tablalibros.getColumnModel().getColumn(4).setHeaderValue("Año publicación");
            tablalibros.getColumnModel().getColumn(5).setHeaderValue("Isbn");
        }

        jLabel1.setText("Editorial");

        jLabel2.setText("Autor");

        jLabel3.setText("Título");

        jLabel4.setText("Id libro");

        jLabel5.setText("Año publicación");

        jLabel6.setText("Isbn");

        crearlibro.setText("Crear libro");
        crearlibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearlibroActionPerformed(evt);
            }
        });

        actualizarlibro.setText("Actualizar libro");
        actualizarlibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarlibroActionPerformed(evt);
            }
        });

        leerlibro.setText("Leer libro");
        leerlibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leerlibroActionPerformed(evt);
            }
        });

        eliminarlibro.setText("Eliminar libro");
        eliminarlibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarlibroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(crearlibro)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idlibrofield)
                    .addComponent(isbnlibrofield)
                    .addComponent(añolibrofield)
                    .addComponent(editoriallibrofield)
                    .addComponent(titulolibrofield)
                    .addComponent(autorlibrofield)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(leerlibro)
                        .addGap(53, 53, 53)
                        .addComponent(actualizarlibro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(eliminarlibro)
                        .addGap(23, 23, 23)))
                .addGap(458, 458, 458))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(idlibrofield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(titulolibrofield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(autorlibrofield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(editoriallibrofield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(añolibrofield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(isbnlibrofield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(crearlibro)
                    .addComponent(leerlibro)
                    .addComponent(actualizarlibro)
                    .addComponent(eliminarlibro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Libros", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 153, 204));

        jPanel3.setBackground(new java.awt.Color(255, 204, 204));

        tablalibros1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Categoria", "Nombre categoria"
            }
        ));
        jScrollPane2.setViewportView(tablalibros1);

        jLabel9.setText("Nombre categoria");

        jLabel10.setText("ID Categoria");

        crearcategoria.setText("Crear categoria");
        crearcategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearcategoriaActionPerformed(evt);
            }
        });

        actualizarcategoria.setText("Actualizar categoria");
        actualizarcategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarcategoriaActionPerformed(evt);
            }
        });

        leercategoria.setText("Leer categoria");
        leercategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leercategoriaActionPerformed(evt);
            }
        });

        eliminarcategoria.setText("Eliminar categoria");
        eliminarcategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarcategoriaActionPerformed(evt);
            }
        });

        nombrecategoriafield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombrecategoriafieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(crearcategoria)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(leercategoria)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(actualizarcategoria)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(eliminarcategoria))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(idcategoriafield, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
                            .addComponent(nombrecategoriafield))))
                .addGap(458, 458, 458))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(idcategoriafield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(nombrecategoriafield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(crearcategoria)
                    .addComponent(leercategoria)
                    .addComponent(actualizarcategoria)
                    .addComponent(eliminarcategoria))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(155, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 630, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 643, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Categorias", jPanel2);

        jPanel6.setBackground(new java.awt.Color(255, 204, 255));

        tablaprestamos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Prestamo_id", "Libro_id", "Usuario_id", "Fecha_prestamo", "Fecha_devolucion"
            }
        ));
        jScrollPane5.setViewportView(tablaprestamos);

        jLabel14.setText("Fecha_prestamo");

        jLabel15.setText("Usuario_id");

        jLabel19.setText("Libro_id");

        jLabel20.setText("Prestamo_id");

        jLabel21.setText("Fecha_devolucion");

        crearprestamo.setText("Crear Prestamo");
        crearprestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearprestamoActionPerformed(evt);
            }
        });

        actualizarprestamo.setText("Actualizar Prestamo");
        actualizarprestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarprestamoActionPerformed(evt);
            }
        });

        leerprestamo.setText("Leer Prestamo");
        leerprestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leerprestamoActionPerformed(evt);
            }
        });

        eliminarprestamo.setText("Eliminar Prestamo");
        eliminarprestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarprestamoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(crearprestamo)
                        .addGap(31, 31, 31)
                        .addComponent(leerprestamo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(actualizarprestamo)
                        .addGap(26, 26, 26)
                        .addComponent(eliminarprestamo)
                        .addGap(22, 22, 22))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(prestamosidfield)
                            .addComponent(fechadevolucionfield)
                            .addComponent(fechaprestamofield)
                            .addComponent(libro_idfield)
                            .addComponent(usuario_idfield))))
                .addGap(458, 458, 458))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(prestamosidfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(libro_idfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(usuario_idfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(fechaprestamofield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fechadevolucionfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addGap(68, 68, 68)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(crearprestamo)
                    .addComponent(leerprestamo)
                    .addComponent(actualizarprestamo)
                    .addComponent(eliminarprestamo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Prestamos", jPanel6);

        jPanel5.setBackground(new java.awt.Color(255, 204, 204));

        tablalibros3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id libro", "Título", "Autor", "Editorial", "Año publicación", "Isbn"
            }
        ));
        jScrollPane4.setViewportView(tablalibros3);
        if (tablalibros3.getColumnModel().getColumnCount() > 0) {
            tablalibros3.getColumnModel().getColumn(2).setHeaderValue("Autor");
            tablalibros3.getColumnModel().getColumn(3).setHeaderValue("Editorial");
            tablalibros3.getColumnModel().getColumn(4).setHeaderValue("Año publicación");
            tablalibros3.getColumnModel().getColumn(5).setHeaderValue("Isbn");
        }

        jLabel16.setText("Categoria id");

        jLabel17.setText("Libro id");

        crearlibro_categoria.setText("Crear Libro_Categoria");
        crearlibro_categoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearlibro_categoriaActionPerformed(evt);
            }
        });

        actualizarlibro_categoria.setText("Actualizar Libro_Categoria");
        actualizarlibro_categoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarlibro_categoriaActionPerformed(evt);
            }
        });

        leerlibro_categoria.setText("Leer Libro_Categoria");
        leerlibro_categoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leerlibro_categoriaActionPerformed(evt);
            }
        });

        eliminarlibro_categoria.setText("Eliminar Libro_Categoria");
        eliminarlibro_categoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarlibro_categoriaActionPerformed(evt);
            }
        });

        libroidfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                libroidfieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(categoriaidfield, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(libroidfield, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(leerlibro_categoria)
                                    .addComponent(crearlibro_categoria))
                                .addGap(140, 140, 140)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(eliminarlibro_categoria, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(actualizarlibro_categoria, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(150, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(libroidfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(categoriaidfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(crearlibro_categoria)
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(eliminarlibro_categoria)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(actualizarlibro_categoria)
                    .addComponent(leerlibro_categoria))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(105, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Libro_Categoria", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void crearlibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearlibroActionPerformed
        LibroController libro= new LibroController();
        libro.crearLibro(titulolibrofield.getText(), autorlibrofield.getText(), editoriallibrofield.getText(), Integer.parseInt(añolibrofield.getText()), isbnlibrofield.getText());
    }//GEN-LAST:event_crearlibroActionPerformed

    private void leerlibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leerlibroActionPerformed
        DefaultTableModel model = (DefaultTableModel) tablalibros.getModel();
        model.setRowCount(0);
        ArrayList<Libro> libros = new ArrayList();
        LibroController libro = new LibroController();
        List<Libro> leer = libro.leerLibros();
        libros.addAll(leer);

        Object columnas[] = new Object[6];
        for(Libro c : libros){
            columnas[0]=c.getId_libro();
            columnas [1]=c.getTitulo();
            columnas [2]=c.getAutor();
            columnas [3]=c.getEditorial();
            columnas [4]=c.getAnio_publicacion();
            columnas [5]=c.getIsbn();
            model.addRow(columnas);
        }

    }//GEN-LAST:event_leerlibroActionPerformed

    private void eliminarlibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarlibroActionPerformed
        LibroController libro= new LibroController();
       libro.eliminarLibros(Integer.parseInt(idlibrofield.getText()));
    }//GEN-LAST:event_eliminarlibroActionPerformed

    private void crearcategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearcategoriaActionPerformed
        CategoriaController categoria= new CategoriaController();
        categoria.crearCategoria(nombrecategoriafield.getText());
    }//GEN-LAST:event_crearcategoriaActionPerformed

    private void leercategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leercategoriaActionPerformed
        DefaultTableModel model = (DefaultTableModel) tablalibros1.getModel();
        model.setRowCount(0);
        ArrayList<Categoria> categorias = new ArrayList();
        CategoriaController categoria = new CategoriaController(); //intanciar objeto objetod con valores 
        List<Categoria> leer = categoria.leerCategorias(); // categoria 
        categorias.addAll(leer);

        Object columnas[] = new Object[2];
        for(Categoria c : categorias){
            columnas[0]=c.getCategoria_id();
            columnas [1]=c.getNombre();
            model.addRow(columnas);
        }
    }//GEN-LAST:event_leercategoriaActionPerformed

    private void eliminarcategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarcategoriaActionPerformed
      CategoriaController categoria= new CategoriaController();
      categoria.eliminarCategoriaVista(Integer.parseInt(idcategoriafield.getText()));
    }//GEN-LAST:event_eliminarcategoriaActionPerformed

    private void nombrecategoriafieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombrecategoriafieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombrecategoriafieldActionPerformed

    private void actualizarcategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarcategoriaActionPerformed
     CategoriaController categoria= new CategoriaController();
     categoria.actualizarCategoria(Integer.parseInt(idcategoriafield.getText()), nombrecategoriafield.getText());
    }//GEN-LAST:event_actualizarcategoriaActionPerformed

    private void actualizarlibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarlibroActionPerformed
        LibroController libro= new LibroController();
     libro.actualizarLibros(Integer.parseInt(idlibrofield.getText()), titulolibrofield.getText(), autorlibrofield.getText(), editoriallibrofield.getText(), Integer.parseInt(añolibrofield.getText()), isbnlibrofield.getText()); 
    }//GEN-LAST:event_actualizarlibroActionPerformed

    private void crearusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearusuarioActionPerformed
     UsuarioController usuario= new UsuarioController();
     usuario.crearUsuario(nombreusuariofield.getText(), emailusuariofield.getText(), Integer.parseInt(telefonousuariofield.getText()));   
    }//GEN-LAST:event_crearusuarioActionPerformed

    private void actualizarusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarusuarioActionPerformed
      UsuarioController usuario= new UsuarioController();
      usuario.actualizarUsuario(Integer.parseInt(idusuariofield.getText()),nombreusuariofield.getText(), emailusuariofield.getText(), Integer.parseInt(telefonousuariofield.getText()));
    }//GEN-LAST:event_actualizarusuarioActionPerformed

    private void leerusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leerusuarioActionPerformed
        DefaultTableModel model = (DefaultTableModel) tablausuarios.getModel();
        model.setRowCount(0);
        ArrayList<Usuario> usuarios = new ArrayList();
        UsuarioController usuario = new UsuarioController(); //intanciar objeto objetod con valores 
        List<Usuario> leer = usuario.leerUsuario(); // categoria 
        usuarios.addAll(leer);

        Object columnas[] = new Object[4];
        for(Usuario u : usuarios){
            columnas[0]=u.getId_usuario();
            columnas [1]=u.getNombre();
            columnas [2]=u.getEmail();
            columnas [3]=u.getTelefono();
            model.addRow(columnas);
        }
                                                 
    }//GEN-LAST:event_leerusuarioActionPerformed

    private void eliminarusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarusuarioActionPerformed
      UsuarioController usuario= new UsuarioController();
      usuario.eliminarUsuarios(Integer.parseInt(idusuariofield.getText()));
    }//GEN-LAST:event_eliminarusuarioActionPerformed

    private void crearprestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearprestamoActionPerformed
        PrestamoController prestamo= new PrestamoController();
        prestamo.crearPrestamo(Integer.parseInt(libro_idfield.getText()), Integer.parseInt(usuario_idfield.getText()), fechaprestamofield.getText(), fechadevolucionfield.getText());
    }//GEN-LAST:event_crearprestamoActionPerformed

    private void actualizarprestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarprestamoActionPerformed
        PrestamoController prestamo= new PrestamoController();
        prestamo.actualizarPrestamo(Integer.parseInt(libro_idfield.getText()), Integer.parseInt(usuario_idfield.getText()), fechaprestamofield.getText(), fechadevolucionfield.getText());
    }//GEN-LAST:event_actualizarprestamoActionPerformed

    private void leerprestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leerprestamoActionPerformed
        DefaultTableModel model = (DefaultTableModel) tablaprestamos.getModel();
        model.setRowCount(0);
        ArrayList<Prestamo> prestamos = new ArrayList();
        PrestamoController prestamo = new PrestamoController(); //intanciar objeto objetod con valores 
        List<Prestamo> leer = prestamo.leerPrestamo(); // categoria 
        prestamos.addAll(leer);
        
        Object columnas[] = new Object[4];
        for(Prestamo u : prestamos){
            //columnas[0]=u.getPrestamo_id();
            columnas [0]=u.getLibro_id();
            columnas [1]=u.getUsuario_id();
            columnas [2]=u.getFecha_prestamo();
            columnas [3]=u.getFecha_devolucion();
            model.addRow(columnas);
        }
    }//GEN-LAST:event_leerprestamoActionPerformed

    private void eliminarprestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarprestamoActionPerformed
      PrestamoController prestamo= new PrestamoController();
      prestamo.eliminarPrestamos(Integer.parseInt(prestamosidfield.getText()));
    }//GEN-LAST:event_eliminarprestamoActionPerformed

    private void libroidfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_libroidfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_libroidfieldActionPerformed

    private void eliminarlibro_categoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarlibro_categoriaActionPerformed

    }//GEN-LAST:event_eliminarlibro_categoriaActionPerformed

    private void leerlibro_categoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leerlibro_categoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_leerlibro_categoriaActionPerformed

    private void actualizarlibro_categoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarlibro_categoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_actualizarlibro_categoriaActionPerformed

    private void crearlibro_categoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearlibro_categoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_crearlibro_categoriaActionPerformed

    private void idusuariofieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idusuariofieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idusuariofieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizarcategoria;
    private javax.swing.JButton actualizarlibro;
    private javax.swing.JButton actualizarlibro_categoria;
    private javax.swing.JButton actualizarprestamo;
    private javax.swing.JButton actualizarusuario;
    private javax.swing.JTextField autorlibrofield;
    private javax.swing.JTextField añolibrofield;
    private javax.swing.JTextField categoriaidfield;
    private javax.swing.JButton crearcategoria;
    private javax.swing.JButton crearlibro;
    private javax.swing.JButton crearlibro_categoria;
    private javax.swing.JButton crearprestamo;
    private javax.swing.JButton crearusuario;
    private javax.swing.JTextField editoriallibrofield;
    private javax.swing.JButton eliminarcategoria;
    private javax.swing.JButton eliminarlibro;
    private javax.swing.JButton eliminarlibro_categoria;
    private javax.swing.JButton eliminarprestamo;
    private javax.swing.JButton eliminarusuario;
    private javax.swing.JTextField emailusuariofield;
    private javax.swing.JTextField fechadevolucionfield;
    private javax.swing.JTextField fechaprestamofield;
    private javax.swing.JTextField idcategoriafield;
    private javax.swing.JTextField idlibrofield;
    private javax.swing.JTextField idusuariofield;
    private javax.swing.JTextField isbnlibrofield;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton leercategoria;
    private javax.swing.JButton leerlibro;
    private javax.swing.JButton leerlibro_categoria;
    private javax.swing.JButton leerprestamo;
    private javax.swing.JButton leerusuario;
    private javax.swing.JTextField libro_idfield;
    private javax.swing.JTextField libroidfield;
    private javax.swing.JTextField nombrecategoriafield;
    private javax.swing.JTextField nombreusuariofield;
    private javax.swing.JTextField prestamosidfield;
    private javax.swing.JTable tablalibros;
    private javax.swing.JTable tablalibros1;
    private javax.swing.JTable tablalibros3;
    private javax.swing.JTable tablaprestamos;
    private javax.swing.JTable tablausuarios;
    private javax.swing.JTextField telefonousuariofield;
    private javax.swing.JTextField titulolibrofield;
    private javax.swing.JTextField usuario_idfield;
    // End of variables declaration//GEN-END:variables
}
